FROM rust:1.91-bookworm AS builder
WORKDIR /app
COPY realtime-split ./realtime-split
WORKDIR /app/realtime-split
RUN cargo build --release -p kotatsu-api-server-split

FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates && rm -rf /var/lib/apt/lists/*
COPY --from=builder /app/realtime-split/target/release/kotatsu-api-server-split /usr/local/bin/api-server
CMD ["/usr/local/bin/api-server"]
