name = "kotatsu-backend"
main = "src/worker.ts"
compatibility_date = "2026-03-17"

[vars]
APP_NAME = "kotatsu-backend"

[[kv_namespaces]]
binding = "GAME_KV"
id = "REPLACE_WITH_PROD_KV_ID"
preview_id = "REPLACE_WITH_PREVIEW_KV_ID"
