FROM rust:1.91-bookworm AS builder
WORKDIR /app
COPY . .
RUN cargo build --release -p kotatsu-realtime-server-split

FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY --from=builder /app/target/release/kotatsu-realtime-server-split /usr/local/bin/realtime-server
CMD ["/usr/local/bin/realtime-server"]
