name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: realtime-split
      - name: Cargo check
        run: cargo check --manifest-path realtime-split/Cargo.toml
      - name: Cargo test
        run: cargo test --manifest-path realtime-split/Cargo.toml
